### PR TITLE
added one dark theme

### PR DESCRIPTION
**Pull request by wr4ckr**
image
image

### CODE REVIEW

**Review by Extravi — APPROVED** [review]

**Comment by Extravi** [comment]
thank you :smile:

**Comment by Extravi** [comment]
sorry there was some strange bug with settings i might add it back later

**Comment by Extravi** [comment]
#4

**Comment by kek1211** [comment]
strange
image
on my instance everything is fine

**Comment by Extravi** [comment]
yeah but when you set it back to dark it still says one dark

**Pull request merged**
